using './main.bicep'

param namePrefix = 'wl01'
param storagesku = 'Standard_LRS'
param location = 'eastus2'
param subnetName = 'PrivateLink-subnet'
param vnetName = 'js-hub-vnet'
param vnetResourceGroup = 'js-core-rg'
param privateEndpointName = '${namePrefix}-pe'
param functionAppName = '${namePrefix}-function-app'
